### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by pedrodj7878** [KishanBagaria/AirDoS#4]
Hi KushanBangaria,

thank you for your work :)

***
python3 AirDoS.py
Traceback (most recent call last):
  File "AirDoS.py", line 17, in <module>
    from opendrop.client import AirDropBrowser, AirDropClient
  File "C:\Users\Kali\AppData\Local\Programs\Python\Python38-32\lib\site-packages\opendrop\client.py", line 30, in <module>
    import libarchive
  File "C:\Users\Kali\AppData\Local\Programs\Python\Python38-32\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\Kali\AppData\Local\Programs\Python\Python38-32\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\Kali\AppData\Local\Programs\Python\Python38-32\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\Kali\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Kali\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 359, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
***

Any suggestion?

**Comment by KishanBagaria** [comment]
Not sure if this will work on Windows, you can try https://github.com/seemoo-lab/opendrop

If opendrop doesn't work too, this script won't work.
